CREATE DATABASE nk_ts;

CREATE TABLE posts(
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    desciption TEXT NOT NULL,
    image_url TEXT,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE posts;